// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tutorial

type User struct {
	ID        int64
	Firstname string
	Lastname  string
	Email     string
	Password  string
}
