// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package tutorial

import (
	"context"
)

const checkEmail = `-- name: CheckEmail :one
SELECT email FROM public.users WHERE email = $1
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, checkEmail, email)
	err := row.Scan(&email)
	return email, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO public.users (firstname, lastname, email, password)
VALUES ($1, $2, $3, $4)
RETURNING id, firstname, lastname, email
`

type CreateUserParams struct {
	Firstname string
	Lastname  string
	Email     string
	Password  string
}

type CreateUserRow struct {
	ID        int64
	Firstname string
	Lastname  string
	Email     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firstname, lastname, email, password
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
	)
	return i, err
}
