// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Service struct {
	ProviderID  int64
	PetSitting  bool
	DogWalking  bool
	PetDayCare  bool
	PetGrooming bool
	PetTraining bool
	PetMassage  bool
}

type User struct {
	ID                int64
	Firstname         string
	Lastname          string
	Email             string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
	Password          string
}
