// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BookedService struct {
	ID          int64
	CustomerID  int64
	ProviderID  int64
	ServiceType string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Service struct {
	ProviderID       int64
	PetSitting       bool
	DogWalking       bool
	PetDayCare       bool
	PetGrooming      bool
	PetTraining      bool
	PetMassage       bool
	PetSittingPrice  pgtype.Numeric
	DogWalkingPrice  pgtype.Numeric
	PetDayCarePrice  pgtype.Numeric
	PetGroomingPrice pgtype.Numeric
	PetTrainingPrice pgtype.Numeric
	PetMassagePrice  pgtype.Numeric
}

type User struct {
	ID                int64
	Firstname         string
	Lastname          string
	Email             string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
	Password          string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
