// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmail = `-- name: CheckEmail :one
SELECT email FROM public.users WHERE email = $1
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, checkEmail, email)
	err := row.Scan(&email)
	return email, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO public.users (firstname, lastname, email, password, isCustomer, isServiceProvider,isAdmin)
VALUES ($1, $2, $3, $4,$5,$6, $7)
RETURNING id, firstname, lastname, email, isCustomer,isServiceProvider,isAdmin
`

type CreateUserParams struct {
	Firstname         string
	Lastname          string
	Email             string
	Password          string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
}

type CreateUserRow struct {
	ID                int64
	Firstname         string
	Lastname          string
	Email             string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
		arg.Iscustomer,
		arg.Isserviceprovider,
		arg.Isadmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Iscustomer,
		&i.Isserviceprovider,
		&i.Isadmin,
	)
	return i, err
}

const deleteServices = `-- name: DeleteServices :exec
DELETE FROM public.services WHERE provider_id = $1
`

func (q *Queries) DeleteServices(ctx context.Context, providerID int64) error {
	_, err := q.db.Exec(ctx, deleteServices, providerID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM public.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getProviders = `-- name: GetProviders :many
SELECT id, firstname, lastname, email, iscustomer, isserviceprovider, isadmin, password, created_at, updated_at FROM users WHERE isServiceProvider = true LIMIT $1 OFFSET $2
`

type GetProvidersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetProviders(ctx context.Context, arg GetProvidersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getProviders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Iscustomer,
			&i.Isserviceprovider,
			&i.Isadmin,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolebyID = `-- name: GetRolebyID :one
SELECT id, isAdmin, isCustomer, isServiceProvider
FROM users
WHERE id = $1
`

type GetRolebyIDRow struct {
	ID                int64
	Isadmin           bool
	Iscustomer        bool
	Isserviceprovider bool
}

func (q *Queries) GetRolebyID(ctx context.Context, id int64) (GetRolebyIDRow, error) {
	row := q.db.QueryRow(ctx, getRolebyID, id)
	var i GetRolebyIDRow
	err := row.Scan(
		&i.ID,
		&i.Isadmin,
		&i.Iscustomer,
		&i.Isserviceprovider,
	)
	return i, err
}

const getServiceByProviderID = `-- name: GetServiceByProviderID :one
SELECT provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage FROM public.services WHERE provider_id = $1
`

func (q *Queries) GetServiceByProviderID(ctx context.Context, providerID int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByProviderID, providerID)
	var i Service
	err := row.Scan(
		&i.ProviderID,
		&i.PetSitting,
		&i.DogWalking,
		&i.PetDayCare,
		&i.PetGrooming,
		&i.PetTraining,
		&i.PetMassage,
	)
	return i, err
}

const getServices = `-- name: GetServices :many
SELECT provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage FROM public.services
`

func (q *Queries) GetServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ProviderID,
			&i.PetSitting,
			&i.DogWalking,
			&i.PetDayCare,
			&i.PetGrooming,
			&i.PetTraining,
			&i.PetMassage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firstname, lastname, email, password,isCustomer,isServiceProvider,isAdmin
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                int64
	Firstname         string
	Lastname          string
	Email             string
	Password          string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Iscustomer,
		&i.Isserviceprovider,
		&i.Isadmin,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, firstname, lastname, email, iscustomer, isserviceprovider, isadmin, password, created_at, updated_at
FROM public.users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Iscustomer,
		&i.Isserviceprovider,
		&i.Isadmin,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, firstname, lastname, email, iscustomer, isserviceprovider, isadmin, password, created_at, updated_at FROM public.users 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Iscustomer,
			&i.Isserviceprovider,
			&i.Isadmin,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeReservation = `-- name: MakeReservation :one
INSERT INTO public.booked_service (customer_id, provider_id, service_type, start_time, end_time)
SELECT $1, $2, $3, $4, $5
WHERE NOT EXISTS (
    SELECT 1
    FROM public.booked_service
    WHERE customer_id = $1
      AND service_type = $3
      AND start_time < $5
      AND end_time > $4
)
RETURNING id, customer_id, provider_id, service_type, start_time, end_time
`

type MakeReservationParams struct {
	CustomerID  int64
	ProviderID  int64
	ServiceType string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
}

type MakeReservationRow struct {
	ID          int64
	CustomerID  int64
	ProviderID  int64
	ServiceType string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
}

func (q *Queries) MakeReservation(ctx context.Context, arg MakeReservationParams) (MakeReservationRow, error) {
	row := q.db.QueryRow(ctx, makeReservation,
		arg.CustomerID,
		arg.ProviderID,
		arg.ServiceType,
		arg.StartTime,
		arg.EndTime,
	)
	var i MakeReservationRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProviderID,
		&i.ServiceType,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const updateServices = `-- name: UpdateServices :exec
UPDATE public.services SET pet_sitting = $2 ,dog_walking= $3,pet_day_care=$4,pet_grooming=$5,pet_training=$6,pet_massage=$7
WHERE provider_id =$1
`

type UpdateServicesParams struct {
	ProviderID  int64
	PetSitting  bool
	DogWalking  bool
	PetDayCare  bool
	PetGrooming bool
	PetTraining bool
	PetMassage  bool
}

func (q *Queries) UpdateServices(ctx context.Context, arg UpdateServicesParams) error {
	_, err := q.db.Exec(ctx, updateServices,
		arg.ProviderID,
		arg.PetSitting,
		arg.DogWalking,
		arg.PetDayCare,
		arg.PetGrooming,
		arg.PetTraining,
		arg.PetMassage,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE public.users SET firstname=$2,lastname=$3,email=$4,password=$5,updated_at = now()
WHERE id=$1
`

type UpdateUserParams struct {
	ID        int64
	Firstname string
	Lastname  string
	Email     string
	Password  string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
	)
	return err
}

const upsertServices = `-- name: UpsertServices :one
INSERT INTO public.services (
    provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider_id) DO UPDATE
SET pet_sitting  = EXCLUDED.pet_sitting,
    dog_walking  = EXCLUDED.dog_walking,
    pet_day_care = EXCLUDED.pet_day_care,
    pet_grooming = EXCLUDED.pet_grooming,
    pet_training = EXCLUDED.pet_training,
    pet_massage  = EXCLUDED.pet_massage
RETURNING provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage
`

type UpsertServicesParams struct {
	ProviderID  int64
	PetSitting  bool
	DogWalking  bool
	PetDayCare  bool
	PetGrooming bool
	PetTraining bool
	PetMassage  bool
}

func (q *Queries) UpsertServices(ctx context.Context, arg UpsertServicesParams) (Service, error) {
	row := q.db.QueryRow(ctx, upsertServices,
		arg.ProviderID,
		arg.PetSitting,
		arg.DogWalking,
		arg.PetDayCare,
		arg.PetGrooming,
		arg.PetTraining,
		arg.PetMassage,
	)
	var i Service
	err := row.Scan(
		&i.ProviderID,
		&i.PetSitting,
		&i.DogWalking,
		&i.PetDayCare,
		&i.PetGrooming,
		&i.PetTraining,
		&i.PetMassage,
	)
	return i, err
}
