// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const checkEmail = `-- name: CheckEmail :one
SELECT email FROM public.users WHERE email = $1
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, checkEmail, email)
	err := row.Scan(&email)
	return email, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO public.users (firstname, lastname, email, password, isCustomer, isServiceProvider,isAdmin)
VALUES ($1, $2, $3, $4,$5,$6, $7)
RETURNING id, firstname, lastname, email, isCustomer,isServiceProvider,isAdmin
`

type CreateUserParams struct {
	Firstname         string
	Lastname          string
	Email             string
	Password          string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
}

type CreateUserRow struct {
	ID                int64
	Firstname         string
	Lastname          string
	Email             string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
		arg.Iscustomer,
		arg.Isserviceprovider,
		arg.Isadmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Iscustomer,
		&i.Isserviceprovider,
		&i.Isadmin,
	)
	return i, err
}

const getRolebyID = `-- name: GetRolebyID :one
SELECT id, isAdmin, isCustomer, isServiceProvider
FROM users
WHERE id = $1
`

type GetRolebyIDRow struct {
	ID                int64
	Isadmin           bool
	Iscustomer        bool
	Isserviceprovider bool
}

func (q *Queries) GetRolebyID(ctx context.Context, id int64) (GetRolebyIDRow, error) {
	row := q.db.QueryRow(ctx, getRolebyID, id)
	var i GetRolebyIDRow
	err := row.Scan(
		&i.ID,
		&i.Isadmin,
		&i.Iscustomer,
		&i.Isserviceprovider,
	)
	return i, err
}

const getServicesByProvider = `-- name: GetServicesByProvider :one
SELECT provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage
FROM public.services
WHERE provider_id = $1
`

func (q *Queries) GetServicesByProvider(ctx context.Context, providerID int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServicesByProvider, providerID)
	var i Service
	err := row.Scan(
		&i.ProviderID,
		&i.PetSitting,
		&i.DogWalking,
		&i.PetDayCare,
		&i.PetGrooming,
		&i.PetTraining,
		&i.PetMassage,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firstname, lastname, email, password,isCustomer,isServiceProvider,isAdmin
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                int64
	Firstname         string
	Lastname          string
	Email             string
	Password          string
	Iscustomer        bool
	Isserviceprovider bool
	Isadmin           bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Iscustomer,
		&i.Isserviceprovider,
		&i.Isadmin,
	)
	return i, err
}

const upsertServices = `-- name: UpsertServices :one
INSERT INTO public.services (
    provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider_id) DO UPDATE
SET pet_sitting  = EXCLUDED.pet_sitting,
    dog_walking  = EXCLUDED.dog_walking,
    pet_day_care = EXCLUDED.pet_day_care,
    pet_grooming = EXCLUDED.pet_grooming,
    pet_training = EXCLUDED.pet_training,
    pet_massage  = EXCLUDED.pet_massage
RETURNING provider_id, pet_sitting, dog_walking, pet_day_care, pet_grooming, pet_training, pet_massage
`

type UpsertServicesParams struct {
	ProviderID  int64
	PetSitting  bool
	DogWalking  bool
	PetDayCare  bool
	PetGrooming bool
	PetTraining bool
	PetMassage  bool
}

func (q *Queries) UpsertServices(ctx context.Context, arg UpsertServicesParams) (Service, error) {
	row := q.db.QueryRow(ctx, upsertServices,
		arg.ProviderID,
		arg.PetSitting,
		arg.DogWalking,
		arg.PetDayCare,
		arg.PetGrooming,
		arg.PetTraining,
		arg.PetMassage,
	)
	var i Service
	err := row.Scan(
		&i.ProviderID,
		&i.PetSitting,
		&i.DogWalking,
		&i.PetDayCare,
		&i.PetGrooming,
		&i.PetTraining,
		&i.PetMassage,
	)
	return i, err
}
